export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const AUTH_LOADING = 'AUTH_LOADING';
export const LOGIN_USER_SUCCESSFUL = 'LOGIN_USER_SUCCESSFUL';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const SIGNUP_USER_SUCCESSFUL = 'SIGNUP_USER_SUCCESSFUL';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';
export const AUTH_STATE_CHECK = 'AUTH_STATE_CHECK';
export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';

export const ADD_NOTE = 'ADD_NOTE';
export const NOTE_CHANGED = 'NOTE_CHANGED';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS';
